name: Test some stuff
on: [push]
jobs:
    test-encoding-bla:
        runs-on: ubuntu-latest
        steps:
        - name: echo ascii
          run: echo "foo thing"
        - name: echo unicode
          run: |
            echo "♥"
        - name: echo broken quotes
          run: echo "fixed broken quotes"
        - name: echo ok env vars
          run: |
            ls
            pwd
            echo $GITHUB_REPOSITORY
